### PR TITLE
Revert to coffeescript 1.0.17. Version bump to 0.9.0. Closes #13

### LINKED ISSUE #13: Unable to upgrade from Meteor 1.6.0.1 to 1.6.1 because of ClassyTestCase errors
@mitar

Hi,
I'm maintainer of Wekan https://wekan.github.io

I am currently stuck at at Meteor 1.6.0.1 . When I tried to upgrade to 1.6.1, I did first save babel

```
meteor npm install --save @babel/runtime
+ @babel/runtime@7.0.0-beta.38
```

Then I get this error when starting Wekan:

```
The `stylus` package has been deprecated.

To continue using the last supported version
of this package, pin your package version to
2.513.14 (`meteor add stylus@=2.513.14`).
Presence started serverId=G2crLpHP2ybDjcSQB
/home/wekan/repos/wekan/.build/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

ReferenceError: ClassyTestCase is not defined
    at packages/peerlibrary_computed-field.js:258:4
    at packages/peerlibrary_computed-field.js:264:4
    at packages/peerlibrary_computed-field.js:408:3
    at /home/wekan/repos/wekan/.build/bundle/programs/server/boot.js:411:36
    at Array.forEach (<anonymous>)
    at /home/wekan/repos/wekan/.build/bundle/programs/server/boot.js:220:19
    at /home/wekan/repos/wekan/.build/bundle/programs/server/boot.js:471:5
    at Function.run (/home/wekan/repos/wekan/.build/bundle/programs/server/profile.js:510:12)
    at /home/wekan/repos/wekan/.build/bundle/programs/server/boot.js:470:11
```

It looks like this ClassyTestCase issue https://github.com/peerlibrary/meteor-classy-test/issues/13

I did try adding that `peerlibrary:computed-field` as separately cloned to wekan/packages directory like there is already some other in my rebuild-wekan-meteor-1.6.sh script at https://github.com/wekan/wekan-maintainer/tree/master/virtualbox , I did not get it working.

I did also try removing those ClassyTestCase lines with:

```
sed '127,401d' wekan/.build/bundle/programs/server/packages/peerlibrary_computed-field.js
```

But Wekan javascript console did still show ClassyTestCase not defined errors.

Upgrading packages gives unhelpful messages https://github.com/meteor/meteor/issues/3536

I have not found a way to update all meteor packages https://github.com/meteor/meteor/issues/4610

### PR DESCRIPTION
**Pull request by xet7**
Revert to coffeescript 1.0.17.
Version bump to 0.9.0.
Closes #13

### CODE REVIEW

**Comment by mitar** [comment]
Isn't this the same as version 0.7.0?

**Comment by xet7** [comment]
@mitar 

Yes, this reverts to 0.7.0 and adds downgraded dependency coffeescript to 1.0.17 so that this package works on Meteor 1.6.1.

**Comment by xet7** [comment]
@mitar 

Without downgraded dependency to coffeescript 1.0.17 etc it is not possible to upgrade Meteor projects to Meteor 1.6.1.

**Comment by mitar** [comment]
Isn't version 0.7.0 of this package published with coffeescript 1.0.17 already?

**Comment by xet7** [comment]
@mitar 

No, version 0.7.0 does not specify coffeescript version, so it breaks upgrades.

**Comment by mitar** [comment]
> No, version 0.7.0 does not specify coffeescript version, so it breaks upgrades.

It does by specifying `api.versionsFrom`.

**Comment by xet7** [comment]
@mitar 

Specifying api.versionsFrom did not work. Version 0.7.0 is broken. Only specifying coffeescript version 1.0.17 separately fixed this.

**Comment by xet7** [comment]
@mitar 

Without this fix, everyone needs to manually monkey patch like at https://github.com/peerlibrary/meteor-computed-field/issues/13#issuecomment-365400328

**Comment by mitar** [comment]
Why version 1.0.17 and not 1.2.4 of CoffeeScript?

**Comment by xet7** [comment]
@mitar 

I have not tried 1.2.4 yet. Just a moment I try.

**Comment by xet7** [comment]
Yes 1.2.4 works.

**Comment by xet7** [comment]
Hmm, seems to still have errors:

```
This project is already at Meteor 1.6.1, the latest release.
=> Errors while upgrading packages:           
                                              
While selecting package versions:
error: Conflict: Constraint coffeescript@1.2.4 is not satisfied by coffeescript 1.0.17.
Constraints on package "coffeescript":
* coffeescript@1.0.5 <- peerlibrary:blaze-components 0.15.1
* coffeescript@1.0.5 <- peerlibrary:base-component 0.16.0 <- peerlibrary:blaze-components 0.15.1
* coffeescript@1.0.5 <- peerlibrary:reactive-field 0.3.0 <- peerlibrary:base-component 0.16.0 <-
peerlibrary:blaze-components 0.15.1
* coffeescript@1.0.5 <- peerlibrary:reactive-field 0.3.0 <- peerlibrary:blaze-components 0.15.1
* coffeescript@1.2.4 <- peerlibrary:computed-field 0.9.0
* coffeescript@1.0.4 <- softwarerero:accounts-t9n 1.3.11 <- useraccounts:core 1.14.2
* coffeescript@1.0.3 <- 3stack:presence 1.1.2
* coffeescript@1.0.5 <- alethes:pages 1.8.6
* coffeescript@1.0.4 <- arillo:flow-router-helpers 0.5.2
* coffeescript@1.0.4 <- zimme:active-route 2.3.2 <- arillo:flow-router-helpers 0.5.2
* coffeescript@1.0.4 <- tap:i18n 1.8.2
* coffeescript@1.0.4 <- templates:tabs 2.3.0
```

**Comment by xet7** [comment]
Only 1.0.17 works:

```
$ meteor update
This project is already at Meteor 1.6.1, the latest release.
Your top-level dependencies are at their latest compatible versions.
                                              
The following top-level dependencies were not updated to the very latest version available:
 * aldeed:collection2 2.10.0 (3.0.0 is available)
 * matteodem:easy-search 1.6.4 (2.0.0 is available)
 * ongoworks:speakingurl 1.1.0 (9.0.0 is available)
 * peerlibrary:blaze-components 0.15.1 (0.22.0 is available)
                                              
Newer versions of the following indirect dependencies are available:
 * aldeed:collection2-core 1.2.0 (2.1.2 is available)
 * aldeed:schema-deny 1.1.0 (3.0.0 is available)
 * aldeed:schema-index 1.1.1 (3.0.0 is available)
 * coffeescript 1.0.17 (2.2.1_1 is available) 
 * peerlibrary:reactive-field 0.3.0 (0.4.0 is available)
 * softwarerero:accounts-t9n 1.3.11 (2.2.1 is available)
These versions may not be compatible with your project.
To update one or more of these packages to their latest
compatible versions, pass their names to `meteor update`,
or just run `meteor update --all-packages`.
```

**Comment by xet7** [comment]
With this pull request Wekan works with Meteor 1.6.1, Node 8.9.4 and 5.6.0, as you can see from screenshot below. Wekan is used by single private persons to companies that have thousands of users. We really would like to get rid of all of monkey patches and contribute them upstream, so we don't have to fork so much packages. I did yesterday write blog post about benefits of contributing features and bugfixes to upstream https://blog.wekan.team/2018/02/benefits-of-contributing-your-features-to-upstream-wekan/index.html , like contributing features and bugfixes to Wekan. peerlibrary is upstream library that Wekan uses.

wekan-meteor-1 8 1

**Comment by xet7** [comment]
@mitar 

Is there still something to fix in this pull request? What prevents merging and releasing this?

**Comment by mitar** [comment]
As you see from the list above:

```
* coffeescript@1.0.4 <- softwarerero:accounts-t9n 1.3.11 <- useraccounts:core 1.14.2
* coffeescript@1.0.3 <- 3stack:presence 1.1.2
* coffeescript@1.0.5 <- alethes:pages 1.8.6
* coffeescript@1.0.4 <- arillo:flow-router-helpers 0.5.2
* coffeescript@1.0.4 <- zimme:active-route 2.3.2 <- arillo:flow-router-helpers 0.5.2
* coffeescript@1.0.4 <- tap:i18n 1.8.2
* coffeescript@1.0.4 <- templates:tabs 2.3.0
```

These packages are forcing your whole app to be in `1.0` CoffeeScript. I would suggest you also send upstream patches to those packages to upgrade to at least 1.2. Then this 0.7.0 version will work.

**Comment by xet7** [comment]
@mitar 

Thanks! I'll send upstream patches.

**Comment by mitar** [comment]
Can you list what versions of those packages I listed above you have in your app before you upgrade to Meteor 1.6.1?

**Comment by mitar** [comment]
So what I do not understand is why having CoffeeScript 1.2 and 1.0 works in the same app before Meteor 1.6.1.

**Comment by xet7** [comment]
@mitar 

Here is current packages for 1.6.0.1:
https://github.com/wekan/wekan/blob/devel/.meteor/versions

**Comment by mitar** [comment]
So what seems to happen is that after upgrade to Meteor 1.6.1 you can choose only between CoffeeScript 2, CoffeeScript 1.2 or CoffeeScript 1.0. Some packages are on 1.0 (listed above), this package 0.7.0 is on CoffeeScript 1.2 and 0.8.0 on CoffeeScript 2. Sadly, the CoffeeScript 1.0 version of this package is broken.

**Comment by xet7** [comment]
@mitar 

So could these all packages work with CoffeeScript 2 with some package upgrades?

**Comment by mitar** [comment]
Ehm, in `versions` you linked above, you have `coffeescript@1.12.7_3`. This is even newer than 1.2.4 for which this package 0.7.0 was released. So why you cannot keep `coffeescript@1.12.7_3` when upgrading to Meteor 1.6.1?

**Comment by xet7** [comment]
@mitar 

Just a moment I try.

**Comment by mitar** [comment]
> So could these all packages work with CoffeeScript 2 with some package upgrades?

That is a separate process all of packages using CoffeeScript in Meteor will eventually have to do. I have updated many of my own packages (including this one) to CoffeeScript 2 because some users are already using that.

But yes, that would also solve a problem you are having, if everyone just upgrade to CoffeeScript 2.

**Comment by xet7** [comment]
@mitar 

Ok, I'll all pull requests for upgrades to CoffeeScript 2, it's a better solution.

**Comment by mahmost** [comment]
I Agree that the CoffeeScript 2 upgrade is the better long term choice .. I also think that maintaining a 0.7.1 version with this change 1.0.17 is not bad .. just to keep things working with meteor 1.6.1 for now ..

And for the tests to pass .. I think adding package constraint to line 35 in package.js will do the trick

**Comment by xet7** [comment]
@mahmost 

Downgrading to old package is still monkey patching to probably broken versions, and that's already possible. I would like to upgrade all packages instead.

**Comment by xet7** [comment]
@mitar 

Can you release this as v0.7.1 ? I tried to upgrade all dependencies, but got lost in the process.

**Comment by xet7** [comment]
@mitar 

It seems that with these dependencies it's not possible to use `coffeescript@1.12.7_3`, it downgrades to 1.0.17 anyway.

**Comment by xet7** [comment]
> Sadly, the CoffeeScript 1.0 version of this package is broken.

Ok.

**Pull request closed without merging**
